MNEMONIC-733: identified 5 more critical security vulnerabilities
apache/mnemonic pull request #286
Opened 2022-04-03 02:00 UTC by jxjlearn

The whole spark module is excluded temporarily from our build system.
I had to add spark into exclude list of Apache Ant, otherwise it reported license error on those excluded directory.

2022-04-03 02:06 UTC, jxjlearn commented
The build failed, but passed in my local sandbox. I am looking into it. Thanks.

2022-04-03 02:51 UTC, yzz127 requested changes
There are several files related to spark-kmeans depending on spark-core that should also be disabled under mnemonic-bench and several other locations, please check those files and make the change accordingly. Thanks!

2022-04-04 22:42 UTC, jxjlearn commented
As @yzz127 pointed out, failure was due to spark-kmeans-bench module. It has been disabled. In addition, more spark-related items have been disabled in tests and source-assembling settings. Thanks.

2022-04-05 03:23 UTC, yzz127 approved these changes
LGTM, thanks!

2022-04-06 07:49 UTC, bigdata-memory approved these changes
+1, Thank you for remediating the identified vulnerabilities.

2022-04-07 04:28 UTC, merged